language: python
python: '2.7'

env:
  global:
    - exit_code=0
    - number_per_job=2
    - message=()
    - ANSIBLE_VERSION=latest
    - max_retry_count=2
    #- ANSIBLE_VERSION=2.5.5
  matrix:
    - id=1
    - id=2
    - id=3
    - id=4
    - id=5
    - id=6
    - id=7
    - id=8
    - id=9
    - id=10

before_install:
  - sudo apt-get update -qq
  - mkdir ~/.azure
  - touch ~/.azure/credentials
  - printf "[default]\nsubscription_id=${subscriptionId}\nclient_id=${clientId}\nsecret=${secret}\ntenant=${tenant}" > ~/.azure/credentials
  - run_test(){
      file=$1;
      filename=${file##tests/integration/};
      test_name=${file##tests/integration/targets/};
      test_name=${test_name%%/tasks/main.yml};
      m=1;

      echo Run test $test_name from $filename;
      resource_group="asb-roletest-${test_name##azure_rm_}$(date +%s)";
      resource_group_secondary="asb-roletest-${test_name##azure_rm_}$(date +%s)2nd";
      resource_prefix=$(date +%s);

      printf "{\"resource_group\":\"$resource_group\",\n\"test\":\"$filename\",\n\"resource_group_secondary\":\"$resource_group_secondary\",\n\"azure_object_id\":\"$AZURE_OBJECT_ID\",\n\"resource_prefix\":\"$resource_prefix\"}" > ~/arg.json;
      cat ~/arg.json;

      while [ $m -le $max_retry_count ]; do
        echo Run test $m time;

        travis_wait 50 ansible-playbook tests/integration/main.yml;

        if [ $? -ne 0 ]; then
          echo test $test_name failed;

          if [ $m -eq $max_retry_count ]; then
            message+=($test_name);
            export exit_code=1;
          fi;

          m=$[$m+1];
        else
          echo test $test_name passed;
          break;
        fi;
        
      done;
      
    }


  - scan_test() {
      end=$((id * number_per_job));
      start=$((end - number_per_job));

      branch=$TRAVIS_BRANCH;
      echo branch is $branch;
      diffstr=$(git diff $branch remotes/origin/master --name-only  -- * --no-pager);

      liststr=tests/integration/targets/azure_rm_*;
      list=($liststr);

      run_all=false
 
      for item in ${diffstr[*]}; do
        if [[ "$item" != *"main.yml" ]]; then
          if [[ "$item" != *"azure_rm_"*.py ]]; then
            run_all=true;
            break;
          elif [[ "$item" == *"azure_rm_common"*.py ]]; then
            run_all=true;
            break;
          fi
        fi
      done;

      echo run_all is $run_all;
      echo start = $start, end = $end, list_lenth = ${#listall[@]};
      
      if [ "$run_all" == true ]; then
        listfiles=tests/integration/targets/azure_rm_*/tasks/main.yml;
        listall=($listfiles);
        
        for (( i = $start; i < $end; i++ )); do
          if [ "$i" -lt "${#listall[@]}" ]; then
            run_test ${listall[$i]};
          fi;
        done;
      else
        echo start = $start, end = $end, list_lenth = ${#diffstr[@]};
        testlist=();
        for (( i = $start; i < $end; i++ )); do
          if [ "$i" -lt "${#diffstr[@]}" ]; then
            for changedfile in ${diffstr[*]}; do
              arrChanged=(${changedfile//// });
              changedFileName=${arrChanged[-1]};
              echo changedFileName is $changedFileName;
              echo changedfile is $changedfile;

              fileNameNoExtension=${changedFileName#.py};
              if [ -d "tests/intergration/targets/${fileNameNoExtension}" ]; then
                echo run test tests/intergration/targets/${fileNameNoExtension}/tasks/main.yml;
                testlist=("tests/intergration/targets/${fileNameNoExtension}/tasks/main.yml", "${testList[@]}");

              elif [ "$changedFileName" == "main.yml" ]; then
                echo run test $changedfile;
                testList=("${changedfile}" "${testList[@]}");
              else
                for alias in ${list[*]}; do
                  if grep -Fxq "$changedFileName" "${alias}/aliases"; then
                    echo run test $alias;
                    testList=("${alias}/tasks/main.yml", "${testList[@]}");
                    break;
                  fi;
                done;
              fi;
            done;
          fi
        done;
        sorted_unique_testList=($(echo "${testList[@]}" | tr ' ' '\n' | sort -u));
        for test in "${sorted_unique_testList[@]}"; do
          run_test $test;
        done;
      fi
    }

install:
  - if [ "$ANSIBLE_VERSION" == "latest" ]; then pip install ansible[azure]; else pip
    install ansible[azure]==$ANSIBLE_VERSION; fi
  - "{ echo '[defaults]'; echo 'roles_path = ../'; echo 'lookup_plugins = ./tests/integration/targets/azure_rm_keyvaultkey/lookup_plugins'; } >> ansible.cfg"
  - ansible --version
  - pip install -I -r ./files/requirements-azure.txt
  - pip freeze
  - git remote set-branches --add origin master
  - git fetch

script:
  - scan_test
  - exit $exit_code

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    - yungez@microsoft.com

